language: python

os: linux
dist: trusty
group: edge

python:
  - "2.7.12"
  #- "3.5"

perl:
  - "5.24"
  - "5.22"
  - "5.20"


#cd ${HOME}/bin
# Then add symlinks to the executables here, for example:
#ln -s ${HOME}/lib/libspatialindex/spatial spatial

addons:
  apt:
    packages:
      - libspatialindex-dev

#create folders for installation
before_install:
     - chmod +x ./tests/run_tests.sh
     - mkdir -p ${HOME}/bin
     - mkdir -p ${HOME}/lib
     - export PATH="${HOME}/bin:$PATH"
     - cd ${HOME}/lib

# install hicup   
     - wget https://www.bioinformatics.babraham.ac.uk/projects/hicup/hicup_v0.6.1.tar.gz
     - tar -xzf hicup_v0.6.1.tar.gz
     - cd hicup_v0.6.1
     - chmod a+x *
     - cd ${HOME}/bin
     - ln -s ${HOME}/lib/hicup_v0.6.1/* ${HOME}/bin/
     
# install bwa
     - cd ${HOME}/lib
     - wget https://sourceforge.net/projects/bio-bwa/files/bwa-0.7.17.tar.bz2
     - bzip2 -d bwa-0.7.17.tar.bz2 
     - tar -xf bwa-0.7.17.tar
     - cd bwa-0.7.17
     - make
     - cd ${HOME}/bin
     - ln -s ${HOME}/lib/bwa-0.7.17/bwa ${HOME}/bin/

# install GEM
     - cd ${HOME}/lib
     - wget barnaserver.com/gemtools/releases/GEMTools-static-i3-1.7.1.tar.gz
     - tar -xzf GEMTools-static-i3-1.7.1.tar.gz
     - cd ${HOME}/bin
     - ln -s ${HOME}/lib/gemtools-1.7.1-i3/bin/* .

# install  TADbit
     - wget https://github.com/3DGenomes/tadbit/archive/master.zip -O tadbit.zip
     - unzip tadbit.zip
     - cd TADbit-master/
     - pip install scipy
     - pip install matplotlib
     - yes | python setup.py install --install-scripts=${HOME}/bin 
     - cd ${HOME}/bin
     - ls -s 
     - chmod +x tadbit
     - tadbit map
#     - chmod +x ${HOME}/lib/TADbit-master/scripts/tadbit
#     - ln -s ${HOME}/lib/TADbit-master/scripts/tadbit .

     - cd ${HOME}/build/pabloacera/C-HiC/

# command to install dependencies
install:
  - pip install -e .
  - pip install -r requirements.txt

# command to run tests
script: ./tests/run_tests.sh
