language: python

os: linux
dist: trusty
group: edge

python:
  - "2.7"
  #- "3.5"

#cd ${HOME}/bin
# Then add symlinks to the executables here, for example:
#ln -s ${HOME}/lib/libspatialindex/spatial spatial

#create folders for installation
before_install:
    - mkdir -p ${HOME}/bin
    - mkdir -p ${HOME}/lib
    - export PATH="${HOME}/bin:$PATH"
    - cd ${HOME}/lib
    - wget download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz
    - gunzip spatialindex-src-1.8.5.tar.gz
    - tar -xvf spatialindex-src-1.8.5.tar 
 
# command to install dependencies
install:
  - cd spatialindex-src-1.8.5 
  - ./configure
  - make
  - make install
  - pip install .
  - pip install -r requirements.txt

# command to run tests
script: pytest -m "not underdeverlopment"
