language: python

os: linux
dist: trusty
group: edge

python:
  - "2.7.12"
  #- "3.5"

#cd ${HOME}/bin
# Then add symlinks to the executables here, for example:
#ln -s ${HOME}/lib/libspatialindex/spatial spatial
addons:
  apt:
    packages:
      - libspatialindex-dev



#create folders for installation
#before_install:
#    - mkdir -p ${HOME}/bin
#    - mkdir -p ${HOME}/lib
#    - export PATH="${HOME}/bin:$PATH"
#    - export PATH="${HOME}/lib:$PATH"
#    - cd ${HOME}/lib
#    - wget download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz
#    - gunzip spatialindex-src-1.8.5.tar.gz
#    - tar -xvf spatialindex-src-1.8.5.tar 
#    - cd spatialindex-src-1.8.5
#    - ./configure --prefix=${HOME}/lib/spatialindex-src-1.8.5
#    - sudo make
#    - sudo make install

# command to install dependencies
install:
#  - cd ${HOME}/build/pabloacera/C-HiC
  - pip install -e .
  - pip install -r requirements.txt

# command to run tests
script: pytest -m "not underdeverlopment"

#run test in order
jobs:
  include:
    -stage: test
      script: ./test/test_truncater.py
      script: ./test/test_makeRmap_Tool.py
      script: ./test/test_makeBaitmap.py
      script: ./test/test_makeDesignFiles_Tool.py
      script: ./test/test_fastq2bed.py
      script: ./test/test_bed2bamchicago.py
      script: ./test/test_bam2chicago_Tool.py


