language: python

os: linux
dist: trusty
group: edge

python:
  - "2.7.12"
  #- "3.5"

#cd ${HOME}/bin
# Then add symlinks to the executables here, for example:
#ln -s ${HOME}/lib/libspatialindex/spatial spatial
addons:
  apt:
    packages:
      - libspatialindex-dev



#create folders for installation
#before_install:
#    - mkdir -p ${HOME}/bin
#    - mkdir -p ${HOME}/lib
#    - export PATH="${HOME}/bin:$PATH"
#    - export PATH="${HOME}/lib:$PATH"
#    - cd ${HOME}/lib
#    - wget download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz
#    - gunzip spatialindex-src-1.8.5.tar.gz
#    - tar -xvf spatialindex-src-1.8.5.tar 
#    - cd spatialindex-src-1.8.5
#    - ./configure --prefix=${HOME}/lib/spatialindex-src-1.8.5
#    - sudo make
#    - sudo make install

# command to install dependencies
install:
#  - cd ${HOME}/build/pabloacera/C-HiC
  - pip install -e .
  - pip install -r requirements.txt


ignore:
  -test_bam2chicago.py
  -test_bam2chicago_Tool.py
  -test_bed2bamchicago.py
  -test_fastq2bed.py
  -test_gem_indexer.py
  -test_makeBaitmap.py
  -test_makeDesignFiles_Tool.py
  -test_makeRmap_Tool.py
  -test_process_baitmap.py
  -test_process_bam2chicago.py
  -test_process_bed2bam.py
  -test_process_CHiC.py
  -test_process_Design.py
  -test_process_fastq2bed.py
  -test_process_rmap.py
  -test_process_runChicago.py
  -test_runChicago.py
  -test_truncater.py


# command to run tests
script: pytest -m "not underdevelopment"
