language: python

os: linux
dist: trusty
group: edge

python:
  - "2.7.12"
  #- "3.5"

perl:
  - "5.24"
  - "5.22"
  - "5.20"


#cd ${HOME}/bin
# Then add symlinks to the executables here, for example:
#ln -s ${HOME}/lib/libspatialindex/spatial spatial

addons:
  apt:
    packages:
      - libspatialindex-dev
      - samtools
      - bedtools

#create folders for installation
before_install:
     - sudo apt-get install r-base-core
     - sudo apt-get install gawk
     - chmod +x ./tests/run_tests.sh
     - mkdir -p ${HOME}/bin
     - mkdir -p ${HOME}/lib
     - export PATH="${HOME}/bin:$PATH"

#installing chicago
     -  cd ${HOME}/lib
     -  sudo R
     -  source("https://bioconductor.org/biocLite.R")
     -  biocLite("argparser")
     -  biocLite("devtools")
     -  devtools::install_bitbucket("chicagoTeam/Chicago", subdir="Chicago")

     - cd ${HOME}/build/pabloacera/C-HiC/

# command to install dependencies
install:
    - pip install -e .
    - pip install -r requirements.txt
