language: python

os: linux
dist: trusty
group: edge

python:
  - "2.7.12"
  #- "3.5"

perl:
  - "5.24"
  - "5.22"
  - "5.20"


#cd ${HOME}/bin
# Then add symlinks to the executables here, for example:
#ln -s ${HOME}/lib/libspatialindex/spatial spatial

addons:
  apt:
    packages:
      - libspatialindex-dev


#create folders for installation
before_install:
     - chmod +x ./tests/run_tests.sh
     - mkdir -p ${HOME}/bin
     - mkdir -p ${HOME}/lib
     - export PATH="${HOME}/bin:$PATH"
     - cd ${HOME}/lib
     - wget https://www.bioinformatics.babraham.ac.uk/projects/hicup/hicup_v0.6.1.tar.gz
     - tar -xzf hicup_v0.6.1.tar.gz
     - cd hicup_v0.6.1
     - chmod a+x *
     - cd ${HOME}/bin
     - ln -s ${HOME}/lib/hicup_v0.6.1/* ${HOME}/bin/
     - ls -s ${HOME}/lib/hicup_v0.6.1/
     - ls -s 
     - cd ${HOME}/build/pabloacera/C-HiC
     - hicup_truncater


# command to install dependencies
install:
  - pip install -e .
  - pip install -r requirements.txt

# command to run tests
script: ./scripts/test_hicup.sh
